(function(){
  'use strict';
  var games=[],active=null,observer=null;
  var order=['Open World','Racing','FPS','Combat','Wrestling','Fighting','Football','Cricket','Snooker','Carrom','Chess','Cards','Simulation'];
  var $=function(s){return document.querySelector(s)};
  var esc=function(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})};
  function art(g){return (window.NEXARC_COVERS||{})[g.id]||g.thumbnail||''}
  function card(g){return '<button class="card" data-game="'+esc(g.id)+'" aria-label="Play '+esc(g.title)+'"><span class="art" data-src="'+esc(art(g))+'"></span><span class="cardPlay">▶</span><span class="cardText"><b>'+esc(g.title)+'</b><small>'+esc(g.category)+' · AD-FREE · '+esc(g.mobileReady?'MOBILE + DESKTOP':'DESKTOP')+'</small></span></button>'}
  function setArt(el){var src=el.getAttribute('data-src');el.style.backgroundImage=src?'url("'+src.replace(/"/g,'')+'")':'linear-gradient(135deg,#3c0910,#111 55%,#050505)'}
  function loadArt(root){var els=[].slice.call((root||document).querySelectorAll('.art[data-src]'));if(!('IntersectionObserver'in window)){els.forEach(setArt);return}if(!observer)observer=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){setArt(e.target);observer.unobserve(e.target)}})},{rootMargin:'300px'});els.forEach(function(el){observer.observe(el)})}
  function bind(root){[].slice.call((root||document).querySelectorAll('[data-game]')).forEach(function(el){el.onclick=function(){openGame(games.find(function(g){return g.id===el.getAttribute('data-game')}))}});loadArt(root)}
  function render(list){var target=$('#gameRows'),groups={};list.forEach(function(g){(groups[g.category]||(groups[g.category]=[])).push(g)});var cats=Object.keys(groups).sort(function(a,b){return (order.indexOf(a)<0?99:order.indexOf(a))-(order.indexOf(b)<0?99:order.indexOf(b))});target.innerHTML=cats.map(function(cat){return '<section class="row"><div class="rowHead"><h3>'+esc(cat)+'</h3><span>'+groups[cat].length+' '+(groups[cat].length===1?'game':'games')+'</span></div><div class="rail">'+groups[cat].map(card).join('')+'</div></section>'}).join('')||'<div class="empty">No matching games.</div>';$('#gameCount').textContent=list.length+' of '+games.length+' games';bind(target)}
  function filters(){var cats=['All'].concat(order.filter(function(c){return games.some(function(g){return g.category===c})}));$('#filters').innerHTML=cats.map(function(c,i){return '<button class="'+(i?'':'active')+'" data-filter="'+esc(c)+'">'+esc(c)+'</button>'}).join('');[].slice.call(document.querySelectorAll('[data-filter]')).forEach(function(b){b.onclick=function(){document.querySelectorAll('[data-filter]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');var c=b.getAttribute('data-filter');render(c==='All'?games:games.filter(function(g){return g.category===c}))}})}
  function openGame(g){if(!g)return;active=g;$('#playerTitle').textContent=g.title;$('#playerDevice').textContent=g.mobileReady?'MOBILE + DESKTOP':'DESKTOP RECOMMENDED';$('#playerLoading b').textContent='Loading '+g.title+'…';$('#player').classList.add('open');$('#player').classList.remove('loaded');$('#player').setAttribute('aria-hidden','false');$('#gameFrame').src=g.embedUrl;document.body.style.overflow='hidden'}
  function closeGame(){$('#gameFrame').src='about:blank';$('#player').classList.remove('open','loaded');$('#player').setAttribute('aria-hidden','true');document.body.style.overflow='';active=null}
  function search(q){q=q.trim().toLowerCase();var found=q?games.filter(function(g){return (g.title+' '+g.category).toLowerCase().indexOf(q)>-1}):games.slice(0,8);$('#searchResults').innerHTML=found.map(card).join('')||'<div class="empty">No matching games.</div>';bind($('#searchResults'))}
  function wire(){var layer=$('#searchLayer');$('#searchOpen').onclick=function(){layer.classList.add('open');layer.setAttribute('aria-hidden','false');search('');setTimeout(function(){$('#searchInput').focus()},50)};$('#searchClose').onclick=function(){layer.classList.remove('open');layer.setAttribute('aria-hidden','true')};$('#searchInput').oninput=function(){search(this.value)};$('#heroPlay').onclick=function(){openGame(games.find(function(g){return g.id==='apex-street'})||games.find(function(g){return g.featured})||games[0])};$('#playerClose').onclick=closeGame;$('#retry').onclick=function(){if(!active)return;var u=active.embedUrl;$('#player').classList.remove('loaded');$('#gameFrame').src='about:blank';setTimeout(function(){$('#gameFrame').src=u},120)};$('#fullscreen').onclick=function(){var p=$('#player');if(p.requestFullscreen)p.requestFullscreen();else if(p.webkitRequestFullscreen)p.webkitRequestFullscreen()};$('#gameFrame').onload=function(){if(active&&this.src!=='about:blank')$('#player').classList.add('loaded')};document.addEventListener('keydown',function(e){if(e.key==='Escape'){if($('#player').classList.contains('open'))closeGame();else{layer.classList.remove('open');layer.setAttribute('aria-hidden','true')}}})}
  fetch('/games.json?v=20260914-clean1',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('Catalog '+r.status);return r.json()}).then(function(data){games=(data.games||[]).filter(function(g){return g&&g.id&&g.embedUrl&&g.adFree===true}).slice(0,20);filters();render(games);wire();var q=new URLSearchParams(location.search).get('q');if(q){$('#searchOpen').click();$('#searchInput').value=q;search(q)}}).catch(function(){$('#gameRows').innerHTML='<div class="empty">The game catalog could not load. Please refresh.</div>';$('#gameCount').textContent='Unavailable'});
})();
