let allGames=[];let active=null;let heroIndex=0;let heroTimer=null;let loadTimer=null;const rows=document.querySelector('#rows'),count=document.querySelector('#count'),player=document.querySelector('#player'),frame=document.querySelector('#gameFrame'),title=document.querySelector('#playerTitle'),hero=document.querySelector('#featured'),heroTitle=document.querySelector('#heroTitle'),heroMeta=document.querySelector('#heroMeta'),loading=document.querySelector('#loading');
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const verifiedMeta={'ninja-run':{mobileReady:true,sourceSize:'600x800'},'rise-zombies':{mobileReady:true,sourceSize:'1920x1080'},'moto-x3m':{mobileReady:true,sourceSize:'800x600'}};
function card(g){const mobile=g.mobileReady===false?'<span class="deviceBadge">Desktop</span>':'';return `<button class="card" data-id="${esc(g.id)}" aria-label="Play ${esc(g.title)}"><span class="thumb" ${g.thumbnail?`style="background:url('${esc(g.thumbnail)}') center/cover"`:''}></span>${mobile}<span class="cardMeta">${esc(g.title)}</span></button>`}
function render(list=allGames){rows.innerHTML='';const groups={};list.forEach(g=>(groups[g.category||'More Games']??=[]).push(g));Object.entries(groups).forEach(([cat,gs])=>{const el=document.createElement('section');el.className='rowBlock';el.innerHTML=`<h3 class="rowTitle">${esc(cat)}</h3><div class="rail">${gs.map(card).join('')}</div>`;rows.appendChild(el)});if(!list.length)rows.innerHTML='<div class="emptyState">No games found. Try another search.</div>';count.textContent=list===allGames?`${allGames.length} / 120 games`:`${list.length} results · ${allGames.length} total`;document.querySelectorAll('.card').forEach(b=>b.onclick=()=>openGame(allGames.find(g=>String(g.id)===b.dataset.id)))}
function setLoading(msg='Loading game…'){if(loading)loading.textContent=msg}
function openGame(g){if(!g?.embedUrl)return;active=g;title.textContent=g.title;player.classList.add('open');player.classList.remove('loaded');player.setAttribute('aria-hidden','false');setLoading('Loading game…');frame.src=g.embedUrl;document.body.style.overflow='hidden';clearTimeout(loadTimer);loadTimer=setTimeout(()=>{if(active===g&&!player.classList.contains('loaded'))setLoading('Still loading… use Retry if needed.')},12000)}
function closeGame(){clearTimeout(loadTimer);frame.src='about:blank';player.classList.remove('open','loaded');player.setAttribute('aria-hidden','true');document.body.style.overflow='';active=null}
frame.addEventListener('load',()=>{if(frame.src!=='about:blank'){clearTimeout(loadTimer);player.classList.add('loaded')}});document.querySelector('#close').onclick=closeGame;document.querySelector('#retry').onclick=()=>{if(active){player.classList.remove('loaded');setLoading('Reloading game…');frame.src='about:blank';requestAnimationFrame(()=>{frame.src=active.embedUrl})}};document.querySelector('#full').onclick=async()=>{try{await player.requestFullscreen?.()}catch(e){}};
function setHero(i){if(!allGames.length)return;heroIndex=(i+allGames.length)%allGames.length;const g=allGames[heroIndex];heroTitle.textContent=g.title;heroMeta.textContent=`${g.category||'Game'} · Play instantly`;hero.dataset.gameId=g.id;if(g.thumbnail)hero.style.backgroundImage=`linear-gradient(90deg,rgba(0,0,0,.9),rgba(0,0,0,.2)),url('${g.thumbnail}')`;else hero.style.backgroundImage='linear-gradient(115deg,#070707 15%,#240507 55%,#090909 100%)'}function startHero(){clearInterval(heroTimer);setHero(0);heroTimer=setInterval(()=>setHero(heroIndex+1),6500)}
const sp=document.querySelector('#searchPanel'),si=document.querySelector('#searchInput');document.querySelector('#searchBtn').onclick=()=>{sp.classList.add('open');setTimeout(()=>si.focus(),100)};document.querySelector('#searchClose').onclick=()=>{sp.classList.remove('open');si.value='';render()};si.oninput=()=>{const q=si.value.trim().toLowerCase();render(allGames.filter(g=>`${g.title} ${g.category}`.toLowerCase().includes(q)))};document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(player.classList.contains('open'))closeGame();else sp.classList.remove('open')}});document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInterval(heroTimer);else if(allGames.length)startHero()});document.querySelector('#heroPlay').onclick=()=>openGame(allGames[heroIndex]||allGames[0]);
Promise.all(['games.json','data/verified-batch-03.json','data/verified-batch-04.json','data/verified-batch-05.json','data/verified-batch-06.json','data/verified-batch-07.json'].map(p=>fetch(p).then(r=>{if(!r.ok)throw new Error(p);return r.json()}))).then(([master,...batches])=>{const merged=[...(master.games||[]),...batches.flat()];const seen=new Set();allGames=merged.filter(g=>g.embedUrl&&!g.duplicateCandidate&&!seen.has(g.embedUrl)&&seen.add(g.embedUrl)).slice(0,120).map(g=>({...g,...(verifiedMeta[g.id]||{})}));render();startHero()}).catch(()=>{count.textContent='Library unavailable';rows.innerHTML='<div class="emptyState">Games could not load. Please refresh and try again.</div>'});