let allGames=[];let active=null;let heroIndex=0;let heroTimer=null;let loadTimer=null;const rows=document.querySelector('#rows'),count=document.querySelector('#count'),player=document.querySelector('#player'),frame=document.querySelector('#gameFrame'),title=document.querySelector('#playerTitle'),hero=document.querySelector('#featured'),heroTitle=document.querySelector('#heroTitle'),heroMeta=document.querySelector('#heroMeta'),loading=document.querySelector('#loading');
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const gameKey=g=>{try{return new URL(g.embedUrl).pathname.split('/').filter(Boolean)[0]||''}catch(e){return''}};
const art=g=>g.thumbnail||g.image||g.thumb||(gameKey(g)?`https://img.gamemonetize.com/${gameKey(g)}/512x384.jpg`:'');
const fallbackArt=()=>`linear-gradient(135deg,#28070c,#101216 55%,#050505)`;const order=['Action','Racing','Sports','Zombie','Adventure','Arcade','Puzzle'];
function card(g){const image=art(g);return `<button class="card" data-id="${esc(g.id)}" aria-label="Play ${esc(g.title)}"><span class="thumb"${image?` data-art="${esc(image)}"`:''}></span><span class="playBadge">▶</span><span class="cardMeta"><b>${esc(g.title)}</b><small>${esc(g.category||'Game')} · Play Now</small></span></button>`}
function loadArtwork(){document.querySelectorAll('.thumb[data-art]').forEach(el=>{const url=el.dataset.art,img=new Image();img.onload=()=>{el.style.backgroundImage=`url("${url}")`;el.classList.add('artReady')};img.onerror=()=>{el.style.backgroundImage=fallbackArt()};img.src=url})}
function bindCards(){document.querySelectorAll('.card').forEach(b=>b.onclick=()=>openGame(allGames.find(g=>String(g.id)===b.dataset.id)))}
function render(list=allGames){rows.innerHTML='';const groups={};list.forEach(g=>(groups[g.category||'More Games']??=[]).push(g));Object.entries(groups).sort(([a],[b])=>{const ai=order.indexOf(a),bi=order.indexOf(b);return(ai<0?99:ai)-(bi<0?99:bi)||a.localeCompare(b)}).forEach(([cat,gs])=>{const el=document.createElement('section');el.className='rowBlock';el.innerHTML=`<div class="rowHead"><h3 class="rowTitle">${esc(cat)} Games</h3><span>${gs.length} titles</span></div><div class="rail">${gs.map(card).join('')}</div>`;rows.appendChild(el)});if(!list.length)rows.innerHTML='<div class="emptyState">No games found. Try another search.</div>';count.textContent=list===allGames?`${allGames.length} games`:`${list.length} results · ${allGames.length} total`;bindCards();loadArtwork()}
function filterCategory(cat){const c=cat.trim().toLowerCase(),list=c==='all games'?allGames:allGames.filter(g=>(g.category||'').toLowerCase()===c);render(list);document.querySelector('#games')?.scrollIntoView({behavior:'smooth'});document.querySelectorAll('.categoryBar a').forEach(a=>a.classList.toggle('active',a.textContent.trim().toLowerCase()===c))}
function setLoading(msg='Loading game…'){if(loading)loading.textContent=msg}function openGame(g){if(!g?.embedUrl)return;active=g;title.textContent=g.title;player.classList.add('open');player.classList.remove('loaded');player.setAttribute('aria-hidden','false');setLoading(`Loading ${g.title}…`);frame.src=g.embedUrl;document.body.style.overflow='hidden';clearTimeout(loadTimer);loadTimer=setTimeout(()=>{if(active===g&&!player.classList.contains('loaded'))setLoading('Still loading — tap Retry if the game does not appear.')},10000)}function closeGame(){clearTimeout(loadTimer);frame.src='about:blank';player.classList.remove('open','loaded');player.setAttribute('aria-hidden','true');document.body.style.overflow='';active=null}
frame.addEventListener('load',()=>{if(active&&frame.src!=='about:blank'){clearTimeout(loadTimer);player.classList.add('loaded')}});document.querySelector('#close').onclick=closeGame;document.querySelector('#retry').onclick=()=>{if(!active)return;const g=active;player.classList.remove('loaded');setLoading(`Reloading ${g.title}…`);frame.src='about:blank';clearTimeout(loadTimer);setTimeout(()=>{if(active===g){frame.src=g.embedUrl;loadTimer=setTimeout(()=>{if(active===g&&!player.classList.contains('loaded'))setLoading('Still loading — close and try another game if needed.')},10000)}},120)};document.querySelector('#full').onclick=async()=>{try{await(frame.requestFullscreen?.()||player.requestFullscreen?.())}catch(e){try{await player.requestFullscreen?.()}catch(_){}}};
function setHero(i){if(!allGames.length)return;heroIndex=(i+allGames.length)%allGames.length;const g=allGames[heroIndex],image=art(g);heroTitle.textContent=g.title;heroMeta.textContent=`${g.category||'Game'} · Free to play · No download`;hero.dataset.gameId=g.id;if(!image){hero.style.backgroundImage=fallbackArt();return}const probe=new Image();probe.onload=()=>{if(allGames[heroIndex]===g)hero.style.backgroundImage=`linear-gradient(90deg,rgba(2,4,6,.94),rgba(2,4,6,.28)),url("${image}")`};probe.onerror=()=>{if(allGames[heroIndex]===g)hero.style.backgroundImage=fallbackArt()};probe.src=image}function startHero(){clearInterval(heroTimer);setHero(0);heroTimer=setInterval(()=>setHero(heroIndex+1),6500)}
const sp=document.querySelector('#searchPanel'),si=document.querySelector('#searchInput');document.querySelector('#searchBtn').onclick=()=>{sp.classList.add('open');setTimeout(()=>si.focus(),100)};document.querySelector('#searchClose').onclick=()=>{sp.classList.remove('open');si.value='';render()};si.oninput=()=>{const q=si.value.trim().toLowerCase();render(allGames.filter(g=>`${g.title} ${g.category}`.toLowerCase().includes(q)))};document.querySelectorAll('.categoryBar a').forEach(a=>a.onclick=e=>{e.preventDefault();filterCategory(a.textContent)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(player.classList.contains('open'))closeGame();else sp.classList.remove('open')}});document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInterval(heroTimer);else if(allGames.length)startHero()});document.querySelector('#heroPlay').onclick=()=>openGame(allGames[heroIndex]||allGames[0]);
const catalogFiles=['games.json','data/verified-batch-04.json','data/verified-batch-05.json','data/verified-batch-06.json','data/verified-batch-07.json','data/verified-batch-08.json'];const blockedIds=new Set(['fiva-26','football-random','weight-puzzle-alt']);
Promise.all(catalogFiles.map(f=>fetch(`${f}?v=20260911-120`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(f);return r.json()}))).then(parts=>{const pool=parts.flatMap((p,i)=>i===0?(p.games||[]):p),seenUrls=new Set(),seenIds=new Set();allGames=pool.filter(g=>{if(!g?.id||!g?.embedUrl||blockedIds.has(g.id)||g.duplicateCandidate||g.mobileReady===false||seenUrls.has(g.embedUrl)||seenIds.has(g.id))return false;seenUrls.add(g.embedUrl);seenIds.add(g.id);return true}).slice(0,120);render();startHero()}).catch(()=>{count.textContent='Library unavailable';rows.innerHTML='<div class="emptyState">Games could not load. Please refresh and try again.</div>'});